obj-m := yarr2.o
yarr2-objs := \
    utils.o \
    patch.o \
    hook.o \
    hidepid.o \
    hidefile.o \
    yarrcall.o \
    main.o

ccflags-y := -DDEBUG -ggdb -O0
ccflags-y += -I$(src)/../include

